// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRvZIjEouTaZg4UF6YdTyyq6-KyasFZgE',
    appId: '1:892085908483:android:9a797d7b61d72e71aa4a36',
    messagingSenderId: '892085908483',
    projectId: 'diesel-cash-carry',
    storageBucket: 'diesel-cash-carry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkrVnXhhwEavc8vZwd-SALynlFOYjgm6U',
    appId: '1:892085908483:ios:3b58e2ebe21f4f73aa4a36',
    messagingSenderId: '892085908483',
    projectId: 'diesel-cash-carry',
    storageBucket: 'diesel-cash-carry.firebasestorage.app',
    androidClientId: '892085908483-osh3f1tq12d46pb9omsjd8oerebdpnc1.apps.googleusercontent.com',
    iosClientId: '892085908483-0s8q4nq7mv759177e2htpbaad1pvgffn.apps.googleusercontent.com',
    iosBundleId: 'com.qiblax.dieselCash',
  );
}
